---
- name: Install python3-distutils
  package:
    name: python3-distutils
  when: ansible_distribution_release == 'bionic'

- name: Download get-pip.py
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp/

- name: Install pip
  command: "{{python_path}} /tmp/get-pip.py"
