---


- name: Install Pip
  block:
    - name: Module Install
      command: "{{python_path}} -m ensurepip {{python_pip_module_opts}}"
  rescue:
    - name: Download get-pip
      get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp/
    - name: Run get-pip
      command: "{{python_path}} /tmp/get-pip.py"
