---

- name: Add apt key
  apt_key: url={{python_apt_key_url}}
  when: python_apt_repo != ''

- name: Setup apt repository
  apt_repository:
    repo: "{{python_apt_repo}}"
    # temporary fix until https://github.com/ansible/ansible-modules-core/pull/3702 is released
    mode: '0644'
  when: python_apt_repo != ''

- name: Install package
  apt: name={{python_package_name}} update_cache=yes cache_valid_time=86400

- name: Get python version
  shell: "apt-cache show {{python_package_name}} | grep 'Version:' | awk '{print $2}' | cut -d. -f1"
  check_mode: no
  register: python_version_output

- name: Set python_major_version
  set_fact:
    python_major_version: "{{python_version_output.stdout}}"

- name: Get python location
  command: "which python{{python_major_version}}"
  check_mode: no
  register: python_location_output

- name: Set python_path
  set_fact:
    python_path: "{{python_location_output.stdout}}"
