---

# Install package
- include_tasks: install_package.yml
  when: not python_build_from_source

# Build from source
- name: Check if python is already installed
  stat: path="{{python_path}}"
  when: python_build_from_source
  register: python_installed

- include_tasks: build_source.yml
  when: python_build_from_source and python_installed.stat.exists == false

# Install/upgrade pip
- name: Check if pip is already installed
  stat: path="{{python_pip_path}}"
  register: pip_installed

- name: Install pip
  include_tasks: install_pip.yml
  when: pip_installed.stat.exists == false

- name: Add system pip.conf
  template:
    src: pip.conf.j2
    dest: /etc/pip.conf
    owner: root
    group: root
    mode: 0644
  when: python_pip_config is defined

- name: Enusre pip is upgraded
  pip: name=pip state=latest executable="{{python_pip_path}}" umask="{{python_pip_umask}}"

# Install packages
- name: Install virtualenv
  pip: name=virtualenv executable="{{python_pip_path}}" umask="{{python_pip_umask}}"

- name: Install global packages
  pip: name="{{item}}" state=present executable="{{python_pip_path}}" umask="{{python_pip_umask}}"
  with_items: "{{python_global_packages}}"
